### ISSUE TITLE
Support for OCaml 4.12 ?

### ISSUE THREAD

**Issue by AltGr** [nobrakal/asak#4]
Hi!

I am in the process of updating learn-ocaml to OCaml 4.12 (from... 4.05), and found that built-in support has been added for asak. The feature sounds great but this means that I will need an up-to-date version of asak to maintain it!

I've seen that, although the latest version claims support for 4.11 (which is great, changes between 4.11 and 4.12 that concern us should be fairly small), the latest released opam version is 0.2 and compatible only with OCaml up to 4.09.

I'd be very grateful if you could release an update :)

**Comment by nobrakal** [comment]
Hi there,

Just made an opam PR here https://github.com/ocaml/opam-repository/pull/19116

Thanks for the ping and your work on learn-ocaml :)

**Comment by nobrakal** [comment]
The PR was merged, I'll close this now.

**Comment by AltGr** [comment]
Thanks!
